version: "2"
linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - revive
  exclusions:
    paths:
      - frontend/
  settings:
    revive:
      rules:
        - name: exported
          disabled: true
