// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenPath(arg1) {
  return window['go']['main']['DesktopBridge']['OpenPath'](arg1);
}

export function OpenTextFile(arg1) {
  return window['go']['main']['DesktopBridge']['OpenTextFile'](arg1);
}

export function ReadTextFile(arg1) {
  return window['go']['main']['DesktopBridge']['ReadTextFile'](arg1);
}

export function SaveFile(arg1, arg2, arg3) {
  return window['go']['main']['DesktopBridge']['SaveFile'](arg1, arg2, arg3);
}
